#!/bin/bash
if [ -z "${LDV_HOME+xxx}" ]
then 
  echo LDV_HOME is not set
  exit
fi

if [test -f ./provenance.log]
then
   rm -f provenance.log
fi

package=./LDV-package

# make the package
$LDV_HOME/ptu -o $package "$@"
#TBD
mv $package/cde-exec $package/cde-exec.org 2>/dev/null
cp $LDV_HOME/ptu-exec $package/ 2>/dev/null

# Process the ProvenanceDB
python $LDV_HOME/scripts/LDV-prov2dot.py -f $package/provenanceDB.1.log
mv -f $package/provenanceDB.1.log gv/
mv gv $package/
